// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SelfCare.Models;

public partial class Patient
{
    public int PatientId { get; set; }

    public int PractitionerId { get; set; }

    public int? UserId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public Guid PractitionerKey { get; set; }

    public DateOnly DateOfBirth { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string Address3 { get; set; }

    public string Town { get; set; }

    public string County { get; set; }

    public string PostCode { get; set; }

    public string Country { get; set; }

    public DateOnly? ReferalDate { get; set; }

    public string Nhsid { get; set; }

    public int? Gpid { get; set; }

    public DateTime DateUpdated { get; set; }

    public DateTime DateCreated { get; set; }

    public virtual Gp Gp { get; set; }

    public virtual ICollection<Note> Notes { get; set; } = new List<Note>();

    public virtual Practitioner Practitioner { get; set; }
}