// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SelfCare.Models;

public partial class ProductKey
{
    public int ProductId { get; set; }

    public string KeyId { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Practitioner> Practitioners { get; set; } = new List<Practitioner>();
}